steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -ceu
      - |
        echo "deploy job"
        for i in {10..1}; do
          echo "deploy: remaining ${i}s"
          sleep 1
        done
        echo "deploy: done"
options:
  logging: CLOUD_LOGGING_ONLY
