steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -ceu
      - |
        echo "build job"
        echo "_PIPELINE=${_PIPELINE}"
        for i in {10..1}; do
          echo "build: remaining ${i}s"
          sleep 1
        done
        echo "build: done"
options:
  pubsubTopic: projects/<YOUR_PROJECT_ID>/topics/build-status-topic
  logging: CLOUD_LOGGING_ONLY
