steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -ceu
      - |
        echo "deploy job"
substitutions:
  _PIPELINE: deploy
options:
  logging: CLOUD_LOGGING_ONLY
