steps:
  - id: 'wait'
    name: 'bash'
    script: |
      #!/usr/bin/env bash
      # 60秒間、毎秒カウントダウン
      for i in {60..1}; do
        echo "待機中... 残り${i}秒"
        sleep 1
      done
      echo "完了しました！"
tags:
  - deploy

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET