steps:
  - id: cancelot
    name: 'gcr.io/cloud-builders/gcloud-slim'
    entrypoint: bash
    args:
      - -c
      - |
        ./cancelot.sh --tags "build"
    env:
      - 'CURRENT_BUILD_ID=$BUILD_ID'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'REGION=$LOCATION'
  - id: 'wait'
    name: 'bash'
    script: |
      #!/usr/bin/env bash
      # 5秒間、毎秒カウントダウン
      for i in {5..1}; do
        echo "待機中... 残り${i}秒"
        sleep 1
      done
      echo "完了しました！"
  - id: 'submit deploy'
    name: 'gcr.io/cloud-builders/gcloud-slim'
    args:
      - builds 
      - submit 
      - --region=$LOCATION
      - --config=deploy.yaml
tags:
  - build

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET