steps:
  - id: cancelot
    name: 'gcr.io/cloud-builders/gcloud-slim'
    entrypoint: bash
    args:
      - -c
      - |
        ./cancelot.sh --tags "deploy"
    env:
      - 'CURRENT_BUILD_ID=$BUILD_ID'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'REGION=$LOCATION'
  - id: 'wait'
    name: 'bash'
    script: |
      #!/usr/bin/env bash
      # 60秒間、毎秒カウントダウン
      for i in {60..1}; do
        echo "待機中... 残り${i}秒"
        sleep 1
      done
      echo "完了しました！"
tags:
  - deploy

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET