steps:
  - id: 'mask-database'
    name: 'gcr.io/cloud-builders/gcloud-slim'
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - '_DATABASE_PORT=13306'
      - '_INSTANCE_CONNECTION_NAME=${PROJECT_ID}:asia-northeast1:main-clone'
      - 'SERVICE_ACCOUNT=export-mask-database'
    script: |
      #!/usr/bin/env bash
      set -euo pipefail
      apt update -y > /dev/null 2>&1
      apt install -y mysql-client > /dev/null 2>&1
      curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.6.1/cloud-sql-proxy.linux.amd64
      chmod +x cloud-sql-proxy
      ./cloud-sql-proxy --port ${_DATABASE_PORT} ${_INSTANCE_CONNECTION_NAME} &
      PID=$! && echo "Cloud SQL Proxy started - pid: $PID"
      sleep 5 && ./export-masked-data.sh mask_data
      kill $PID && echo "Cloud SQL Proxy killed - pid: $PID"
options:
  logging: CLOUD_LOGGING_ONLY
